### ISSUE TITLE
constrained list options should have data type = String

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#189]
There are two places where constrained list options have the wrong data type displayed. It should always be displayed as String instead:
- If I search for a Constrained List Option (e.g., "MN"), the rows corresponding to list options (e.g., "State::MN") have Constrained List in the Data Type column, but they should have String. 
- If I click on a BEDES atomic term that is a Constrained List and scroll to the bottom where it says "Constrained List Options", the Data Type column is blank, but it should have String.

**Comment by robHitchcock** [comment]
@TravisWalterLBNL I don't know that Constrained List Options currently have a Data Type property. I'm not sure their Data Type should be String since this implies to me that it is a "variable" capable of holding an arbitrary string value. Shouldn't a Data Type of "Constrained List Option" be assigned to them if they have a Data Type property?

**Comment by TravisWalterLBNL** [comment]
@robHitchcock Good point. I agree with Data Type = Constrained List Option. This means the first bullet above is fine as is. I will close this issue and create a new issue addressing the second bullet.
