### ISSUE TITLE
should be able to make all changes to public application

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#192]
If I create an application, then change its sharing from Private to Public, I am no longer allowed to modify the application terms, or the application options (name, description, sharing), but I should be able to.

**Comment by TravisWalterLBNL** [comment]
Significant overlap with issue #207. Let's keep both to make sure all aspects are handled.

**Comment by robHitchcock** [comment]
@wizonesolutions I tested changes on staging.
1. After changing an Application mapping created and owned by me from Private to Public, I cannot edit any of the Application Term properties (Application Term Name, Description, Type of Term, Data Type, Unit).
2. I was able to delete the Mapped Term, but was not then able to select another BEDES term for the mapping.
3. I was able to modify Application Options
4. After changing the Application mapping back from Public to Private, I was able to make all changes, then change the Application back to Public. Was this the intended behavior for making changes only to a Private Application? Or am I supposed to be able to make changes to a Public Application owned by me?
5. After changing the Application mapping back from Public to Private, on the Composite Terms list the terms that had changed from Private to Public automatically when going from Private to Public are still shown as Public in the full list (as expected), however when I select the term for editing it shows Sharing as Private still. This may just be a screen update issue since if I go to edit another term and then back to edit the first term, it shows Sharing as Public.

**Comment by wizonesolutions** [comment]
This one is on production too now.

**Comment by TravisWalterLBNL** [comment]
For clarity, let's move all remaining conversation about this issue to #209 instead (since there is so much overlap).

**Comment by TravisWalterLBNL** [comment]
See #209.
