### ISSUE TITLE
should get warning if user tries to create another copy of a composite term they have already created

### ISSUE THREAD

**Issue by TravisWalterLBNL** [LBNL-ETA/BEDES-Manager#195]
If I have already created a particular composite term (either manually, or by importing from .csv), and then I try to make another copy of that same composite term, when I click "Save", a dialog should pop up that says something like "This composite term already exists. Are you sure you want to create another copy?". The dialog should have a link to the currently existing copy of the composite term. If I click "Yes" in the dialog, a second copy of the composite term should be created (i.e, it should have a different UUID than the original copy). If I click "No", a new copy of the composite term should not be created.

This warning should only occur when there is already another copy of a composite term that is owned by me (either public or private). If another copy of the composite term exists, but it is owned by another user (either public or private), a new copy of the composite term should be created without issuing a warning.

**Comment by wizonesolutions** [comment]
@TravisWalterLBNL I am also restricting this to truly-new composite terms right now. If they edit one that they've already saved and it winds up matching an existing one, the dialog won't be shown. That's because implementing that would introduce the issue of duplicate terms _that they had requested created anyway_ causing the dialog to show every time they edited one of the copies.

Having the dialog only show for new terms (created and unsaved) avoids this set of issues nicely. I suggest we handle them in a follow-up if the functionality is needed.

**Comment by wizonesolutions** [comment]
This is deploying to staging. Have a look in around 20 mins. This is how it looks:

![image](https://user-images.githubusercontent.com/344116/154314042-fd085e03-df74-4a7a-b6a2-7e5048d2f984.png)

**Comment by TravisWalterLBNL** [comment]
Correct. This issue is only referring to an "exact same" composite term (i.e., the same atomic terms and list options, in the same order). If the order is different, it should be considered a different composite term, and this issue should not apply.

**Comment by TravisWalterLBNL** [comment]
Looks good on staging. Will close after testing on production.

**Comment by wizonesolutions** [comment]
Deployed to production.

**Comment by TravisWalterLBNL** [comment]
Fixed on production.
